ignore:
  - "Tests/**/*"
  - "**/*_Tests.swift"
  - "**/*_Mock.swift"
  - "**/*_Vendor.swift"
  - "**/Generated/*.swift"
  - "Sources/StreamChat/StreamStarscream"
  - "Sources/StreamChat/StreamULID"
  - "Sources/StreamChatUI/StreamNuke"
  - "Sources/StreamChatUI/StreamSwiftyGif"
github_checks:
    annotations: false
