flags:
  stream-chat:
    paths:
      - Sources/StreamChat/
  stream-chat-ui:
    paths:
      - Sources/StreamChatUI/
ignore:
  - "Tests/**/*"
  - "**/*_Tests.swift"
  - "**/*_Mock.swift"
  - "**/*_Vendor.swift"
  - "**/Generated/*.swift"
  - "**/Deprecations.swift"
github_checks:
    annotations: false
