sources:
  - ./Generated/OpenAPI/models/ChannelDetailPayload.swift
  - ./Generated/OpenAPI/models/MemberPayload.swift
  - ./Generated/OpenAPI/models/UserPayload.swift
templates:
  - ./Generated/OpenAPIDecodable.stencil
output:
  ./Generated/OpenAPI/OpenAPIDecoders.generated.swift
