//
// Copyright © 2026 Stream.io Inc. All rights reserved.
//

import Foundation

/// A type representing an action produced by a client tool. Actions are expressed
/// as closures that will be executed by whichever component is responsible for
/// handling `ClientToolAction` values.
///
/// Tool implementations generate actions to signal that client-side behavior
/// should occur—such as updating UI, emitting events, or triggering follow-up logic.
public typealias ClientToolAction = () -> Void

/// A protocol for types that can process actions produced by a client tool.
/// Conforming types receive one or more `ClientToolAction` values generated as
/// the result of a tool invocation and decide how they should be applied or executed.
public protocol ClientToolActionHandling: AnyObject {
    /// Handles a list of actions generated by a client tool.
    ///
    /// - Parameter actions: An array of `ClientToolAction` instances describing work
    ///   that should be performed, such as emitting events, updating state, or
    ///   triggering additional client-side behavior.
    func handle(_ actions: [ClientToolAction])
}
