name: 'PR Approvals'
description: 'Get the amount of PR approvals'
runs:
  using: "composite"
  steps:
    - name: Get the amount of PR approvals
      shell: bash
      run: |
        if [ "${{ github.event.review.state }}" == "approved" ]; then
          pr_approvals=$(gh api "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/reviews" | jq '[.[] | select(.state == "APPROVED")] | length')
          echo "PR approvals count: $pr_approvals"
          echo "pr_approvals=$pr_approvals" >> $GITHUB_ENV
        else
          echo "There are no PR approvals"
          echo 'pr_approvals=0' >> $GITHUB_ENV
        fi
