//
// Copyright © 2026 Stream.io Inc. All rights reserved.
//

import Foundation

/// A protocol for types that can process actions produced by a client tool.
/// Conforming types receive one or more `ClientToolAction` values generated as
/// the result of a tool invocation and decide how they should be applied or executed.
public protocol ClientToolActionHandling: AnyObject {
    /// Handles a list of actions generated by a client tool.
    ///
    /// - Parameter actions: An array of `ClientToolAction` instances describing work
    ///   that should be performed, such as emitting events, updating state, or
    ///   triggering additional client-side behavior.
    func handle(_ actions: [ClientToolAction])
}

/// A registry responsible for storing and managing all client tools available
/// to the AI agent. This class handles registration, lookup, and routing of
/// invocation requests to the appropriate tool instance.
public final class ClientToolRegistry {
    /// Internal storage mapping tool names to their corresponding `ClientTool` instances.
    private var toolsByName: [String: any ClientTool] = [:]

    /// Creates a new, empty tool registry.
    public init() {}

    /// Registers a client tool in the registry, making it discoverable by name.
    ///
    /// - Parameter tool: The tool to register. The registry uses the name defined in
    ///   `tool.toolDefinition.name` as the lookup key.
    public func register(tool: any ClientTool) {
        toolsByName[tool.toolDefinition.name] = tool
    }

    /// Produces the set of registration payloads for all registered tools. These
    /// payloads tell the agent the name, description, input schema, and behavior
    /// of each tool.
    ///
    /// - Returns: An array of `ToolRegistrationPayload` describing each registered tool.
    public func registrationPayloads() -> [ToolRegistrationPayload] {
        toolsByName.values.map { tool in
            ToolRegistrationPayload(
                name: tool.toolDefinition.name,
                description: tool.toolDefinition.description ?? tool.instructions,
                instructions: tool.instructions,
                parameters: tool.toolDefinition.inputSchema,
                showExternalSourcesIndicator: tool.showExternalSourcesIndicator
            )
        }
    }

    /// Routes an invocation request to the appropriate tool based on its name.
    /// If the referenced tool does not exist, an empty action array is returned.
    ///
    /// - Parameter invocation: The `ClientToolInvocation` containing the tool name
    ///   and invocation arguments.
    /// - Returns: A list of actions produced by the tool, or an empty array if the
    ///   requested tool is not registered.
    public func handleInvocation(_ invocation: ClientToolInvocation) -> [ClientToolAction] {
        guard let tool = toolsByName[invocation.tool.name] else { return [] }
        return tool.handleInvocation(invocation)
    }
}

/// A protocol representing a client-side tool that the AI agent can invoke.
/// Conforming types define how a tool is described, when it should be displayed, and how it responds to invocations.
public protocol ClientTool: AnyObject {
    /// The static definition of the tool, including its name, description and input schema,
    /// as communicated to the agent.
    var toolDefinition: ClientToolDefinition { get }

    /// Additional usage instructions or human-readable guidance that may be shown to users
    /// or the agent. This supplements the tool definition with contextual tips on
    /// how or when the tool should be used.
    var instructions: String { get }

    /// A Boolean value indicating whether the runtime should show a UI indicator when the tool
    /// relies on external data sources. When `true`, the client may visually signal that calls
    /// to this tool interact with systems outside the local model context.
    var showExternalSourcesIndicator: Bool { get }

    /// Handles an invocation of the tool from the agent. Implementations should inspect
    /// the incoming invocation payload, perform the necessary work, and return one or more
    /// `ClientToolAction` values describing the results or follow-up actions.
    ///
    /// - Parameter invocation: The invocation request containing arguments and metadata provided by the runtime.
    /// - Returns: A list of actions describing the tool’s response to the invocation.
    func handleInvocation(_ invocation: ClientToolInvocation) -> [ClientToolAction]
}

/// The name, description and input schema of a client tool.
///
/// It reads and writes the same JSON as a Model Context Protocol tool (`name`, `description`
/// and `inputSchema`), so a tool defined with the MCP SDK converts without this SDK
/// depending on it:
///
/// ```swift
/// let definition = try ClientToolDefinition(encoding: mcpTool)
/// ```
public struct ClientToolDefinition: Codable, Hashable, Sendable {
    /// The unique name of the tool.
    public var name: String
    /// A description of what the tool does, for the agent.
    public var description: String?
    /// The JSON schema of the tool's arguments.
    public var inputSchema: AIJSONValue?

    public init(name: String, description: String? = nil, inputSchema: AIJSONValue? = nil) {
        self.name = name
        self.description = description
        self.inputSchema = inputSchema
    }

    /// Creates a definition from another tool type that encodes `name`, `description`
    /// and `inputSchema`, such as the MCP SDK's `Tool`.
    public init(encoding tool: some Encodable) throws {
        self = try JSONDecoder().decode(Self.self, from: JSONEncoder().encode(tool))
    }
}

/// Represents a client-side invocation of a tool, including the tool's metadata
/// and any arguments provided by the agent.
public final class ClientToolInvocation {
    /// A descriptor containing metadata about a tool being invoked.
    public final class ToolDescriptor {
        /// The unique name of the tool being invoked.
        public let name: String

        /// A human-readable description of the tool, if provided.
        public let description: String?

        /// Additional instructions or usage guidance associated with the tool.
        public let instructions: String?

        /// The raw-encoded input parameter schema for the tool, typically encoded as JSON.
        public let parameters: Data?

        /// Creates a new tool descriptor.
        ///
        /// - Parameters:
        ///   - name: The unique identifier of the tool.
        ///   - description: A user-facing description of the tool.
        ///   - instructions: Supplementary guidance about how to use the tool.
        ///   - parameters: Raw input schema data, if available.
        public init(
            name: String,
            description: String?,
            instructions: String?,
            parameters: Data?
        ) {
            self.name = name
            self.description = description
            self.instructions = instructions
            self.parameters = parameters
        }
    }

    /// Metadata describing the tool being invoked.
    public let tool: ToolDescriptor

    /// The raw arguments associated with the invocation, typically encoded as JSON.
    public let args: Data?

    /// An optional message identifier associated with the context of the invocation.
    /// This may be used to correlate tool responses to originating messages.
    public let messageId: String?

    /// An optional channel identifier indicating the source or conversational
    /// context in which the invocation occurred.
    public let channelId: AnyHashable?

    /// Creates a new tool invocation containing metadata and raw arguments.
    ///
    /// - Parameters:
    ///   - tool: The descriptor of the tool being invoked.
    ///   - args: Raw encoded arguments supplied for the invocation.
    ///   - messageId: The ID of the associated message, if any.
    ///   - channelId: A channel or thread identifier for contextual routing.
    public init(
        tool: ToolDescriptor,
        args: Data?,
        messageId: String?,
        channelId: AnyHashable?
    ) {
        self.tool = tool
        self.args = args
        self.messageId = messageId
        self.channelId = channelId
    }
}

/// A type representing an action produced by a client tool. Actions are expressed
/// as closures that will be executed by whichever component is responsible for
/// handling `ClientToolAction` values.
///
/// Tool implementations generate actions to signal that client-side behavior
/// should occur—such as updating UI, emitting events, or triggering follow-up logic.
public typealias ClientToolAction = () -> Void

/// A payload describing a tool to the agent during registration.
/// This structure encapsulates the metadata, usage instructions, parameter schema,
/// and optional UI behaviors associated with the tool.
public final class ToolRegistrationPayload: Encodable {
    /// The unique name of the tool. This is how the agent identifies it.
    public let name: String

    /// A user-facing description summarizing the tool's purpose and behavior.
    public let description: String

    /// Optional instructional text offering additional guidance about how or
    /// when to use the tool.
    public let instructions: String?

    /// The tool's expected input parameter schema.
    /// This describes the shape of the arguments the tool accepts.
    public let parameters: AIJSONValue?

    /// Indicates whether the client UI should display an indicator when the tool
    /// interacts with external data sources.
    public let showExternalSourcesIndicator: Bool?

    init(name: String, description: String, instructions: String?, parameters: AIJSONValue?, showExternalSourcesIndicator: Bool?) {
        self.name = name
        self.description = description
        self.instructions = instructions
        self.parameters = parameters
        self.showExternalSourcesIndicator = showExternalSourcesIndicator
    }
}
