#!/usr/bin/env ruby

allure_project_id = 1
allure_endpoint = 'https://streamio.testops.cloud'
allure_regression_testplan = 'Regression Testing'
allure_results_path = 'allure-results'

desc 'Upload test results to Allure TestOps'
lane :allure_upload do |options|
  branch = github_run_details['head_branch']
  allure_args = "-e #{allure_endpoint} --project-id #{allure_project_id} --launch-id #{options[:launch_id]}"
  sh("./xcresults export test_output/StreamChatUITestsApp.xcresult #{allure_results_path}")
  sh("env BRANCH_NAME='#{branch}' ./allurectl upload #{allure_args} #{allure_results_path}")
  UI.success("Check out test results in Allure TestOps: #{allure_endpoint}/launch/#{options[:launch_id]} 🎉")
end

desc 'Create launch on Allure TestOps'
lane :allure_launch do |options|
  next unless check_required?(:e2e)

  tags = []
  github_run = github_run_details
  launch_name =
    if options[:cron]
      'Cron checks'
    elsif ENV['GITHUB_EVENT_NAME'] == 'pull_request'
      pull_request = JSON.parse(ENV['GITHUB_EVENT'])['pull_request']
      tags = pull_request['labels'].map { |label| { name: label['name'] } }
      pull_request['title']
    elsif github_run['head_commit']
      github_run['head_commit']['message']
    else
      github_run['name']
    end
  body = {
    projectId: allure_project_id,
    name: launch_name,
    tags: tags,
    autoclose: false,
    closed: false
  }.to_json
  launch_id = allure_api(path: '/launch', http_method: 'POST', body: body)['id']
  sh("echo 'LAUNCH_ID=#{launch_id}' >> $GITHUB_ENV")
end

desc 'Remove launch on Allure TestOps'
lane :allure_launch_removal do |options|
  allure_api(path: "/launch/#{options[:launch_id]}", http_method: 'DELETE')
end

desc 'Create test-case in Allure TestOps and get its id'
lane :allure_create_testcase do
  body = { projectId: allure_project_id, name: 'Automatically created testcase', deleted: true }.to_json
  testcase_id = allure_api(path: '/testcase', http_method: 'POST', body: body)['id']
  UI.success("#{rocket}\nTestcase with id #{testcase_id} created successfully 🎉")
end

desc 'Sync and run regression test-plan on Allure TestOps'
lane :allure_start_regression do |options|
  UI.user_error!('Link to Jira has to be provided ⚠️') unless options[:jira] =~ URI::DEFAULT_PARSER.regexp[:ABS_URI]
  UI.user_error!('Release version has to be provided ⚠️') if options[:release_version].nil?

  response = allure_api(path: "/testplan/?projectId=#{allure_project_id}", http_method: 'GET')
  testplan_id = response['content'].find { |plan| plan['name'] == allure_regression_testplan }['id']

  allure_api(path: "/testplan/#{testplan_id}/sync", http_method: 'POST')
  UI.success("#{rocket}\nTestplan with id #{testplan_id} synced successfully 🎉")

  body = {
    launchName: "#{allure_regression_testplan} v#{options[:release_version]}",
    links: [{ name: 'Jira', url: options[:jira] }]
  }.to_json
  allure_api(path: "/testplan/#{testplan_id}/run", http_method: 'POST', body: body)
  UI.success("#{rocket}\nTestplan with id #{testplan_id} launched successfully 🎉")
end

desc 'Make a request to Allure TestOps via Rest API'
private_lane :allure_api do |options|
  UI.user_error!('`ALLURE_TOKEN` env var has to be provided ⚠️') if ENV['ALLURE_TOKEN'].nil?

  url = URI("#{allure_endpoint}/api/rs/#{options[:path]}")
  request =
    case options[:http_method].upcase
    when 'GET'
      Net::HTTP::Get.new(url)
    when 'POST'
      Net::HTTP::Post.new(url)
    when 'PATCH'
      Net::HTTP::Patch.new(url)
    when 'DELETE'
      Net::HTTP::Delete.new(url)
    end
  http = Net::HTTP.new(url.host, url.port)
  http.use_ssl = true
  http.verify_mode = OpenSSL::SSL::VERIFY_NONE

  request['authorization'] = "Api-Token #{ENV['ALLURE_TOKEN']}"
  request['content-type'] = 'application/json'
  request.body = options[:body] if options[:body]

  response_body = http.request(request).read_body
  JSON.parse(response_body) if !response_body.nil? && !response_body.empty?
end

def github_run_details
  github_path = "#{ENV['GITHUB_API_URL']}/repos/#{ENV['GITHUB_REPOSITORY']}/actions/runs/#{ENV['GITHUB_RUN_ID']}"
  output = sh(command: "curl -s -H 'authorization: Bearer #{ENV['GITHUB_TOKEN']}' -X GET -G #{github_path}", log: false)
  JSON.parse(output)
end
