fastlane_version "2.68.0"
default_platform :ios

before_all do
  if is_ci
    setup_ci()
  end
end

desc "Installs all Certs and Profiles necessary for development and ad-hoc"
lane :match_me do
  match(
    type: "development",
    app_identifier: [
      "io.getstream.ChatExample",
      "io.getstream.StreamChatClient",
      "io.getstream.StreamChatCore",
      "io.getstream.StreamChat"
    ],
    readonly: true
  )
  
  match(
    type: "adhoc",
    app_identifier: [
      "io.getstream.ChatExample",
      "io.getstream.StreamChatClient",
      "io.getstream.StreamChatCore",
      "io.getstream.StreamChat"
    ],
    readonly: true
  )
end

desc "Builds the latest version with ad-hoc and uploads to firebase"
lane :beta do
  match_me
  
  build_number = increment_build_number(
                   xcodeproj: "./Example/Carthage/ChatExample.xcodeproj",
                   build_number: ENV["GITHUB_SHA"]
                 )

  gym(
    project: "./Example/Carthage/ChatExample.xcodeproj",
    scheme: "ChatExample",
    configuration: "Debug",
    export_method: "ad-hoc",
    export_options: "./fastlane/beta_gym_export_options.plist",
    silent: true,
    clean: true,
    include_symbols: true,
    output_directory: "./dist"
  )
  
  message = changelog_from_git_commits(commits_count: 10)
  
  firebase_app_distribution(
      app: "1:674907137625:ios:10131789dab2e7cad7f348",
      groups: "ios-stream-testers",
      release_notes: message
  )
end
