# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # register_device(name: "iPhone 6", udid: "")
  
  get_certificates
  get_provisioning_profile(
    adhoc: true,
    # force: true
  )
  
  # build your iOS app
  build_app(
    scheme: "GetStreamChat",
    workspace: "GetStreamChat.xcworkspace",
    include_bitcode: true,
    export_method: "ad-hoc",
    export_options: {iCloudContainerEnvironment: "Production"}
  )
  
  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "2ae916eaa00e73d398864ff4e5f3e331e8d31d12",
    build_secret: "c95d35d5b41b05cb53c85b2a94cccb64d1cc6dda73ab19a0f53c3bcff6f67a8d"
  )
end
