#!/bin/bash

set -e  # exit on a non-zero return code from a command

TARGET=""
HOSTING_BASE_PATH="stream-chat-swift"

while [[ $# -gt 0 ]]
do
  case $1 in
    -t|--target)
    TARGET="$2"
    echo "> Following target was provided to the script: $TARGET"
    shift # past argument
    continue;;
    *)
    break;;
  esac
done

export DOCC_JSON_PRETTYPRINT=YES

build() {
  xcodebuild docbuild \
    -scheme "${TARGET}" \
    -derivedDataPath ./derivedData \
    -destination 'platform=iOS Simulator,name=iPhone 12'

  $(xcrun --find docc) process-archive \
  transform-for-static-hosting "derivedData/Build/Products/Debug-iphonesimulator/${TARGET}.doccarchive" \
  --output-path ./docs \
  --hosting-base-path "${HOSTING_BASE_PATH}"
}

clean() {
  rm -rf derivedData
}

build
clean
