name: 'Python Cache'
description: 'Cache Python dependencies'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
    - run: pip3 install -r requirements.txt --break-system-packages
      shell: bash
