name: Cancel obsolete workflows

on: [push]

jobs:
  cancel-obsolete-workflows:
    name: 'Cancel obsolete workflows'
    runs-on: macos-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: "smoke-checks.yml, distribute-test-build.yml" # Workflow file names to cancel
          access_token: ${{ github.token }}
