name: Test Flight Deploy DemoApp

on:
  push:
    branches: [ testflight-test ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache RubyGems
        uses: actions/cache@v2
        id: rubygem-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ env.ImageVersion }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.ImageVersion }}-gem-
      - name: Deploy Demo app
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
        run: bundle exec fastlane testflight_build
          
          
