name: Test Flight Deploy DemoApp

on:
  push:
    branches: [ testflight-test ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Demo app
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
        run: bundle exec fastlane testflight_build
          
          
