name: Distribute Firebase Test Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  HOMEBREW_NO_INSTALL_CLEANUP=1: 1 # Disable cleanup for homebrew, we don't need it on CI

jobs:
  demo:
    name: Distribute Demo App
    runs-on: macos-latest
    steps:
    - name: Install Bot SSH Key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}
    - uses: actions/checkout@v1
    - uses: ./.github/actions/set-build-image-var
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.ImageVersion }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-${{ env.ImageVersion }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - uses: ./.github/actions/bootstrap
    - name: Install firebase-tools
      run: npm install -g firebase-tools
    - name: Distribute Demo app
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: bundle exec fastlane distribute_demo_app
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "You shall not pass!"
        job_name: "Distribute Demo App"
        fields: message,commit,author,action,eventName,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: ${{ github.event_name == 'push' && failure() }}
