name: Publish Docusaurus to prod

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  push_docusaurus:
    name: Publish docusaurus docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: 'production'
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
