name: "Merge main to develop"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.ADMIN_API_TOKEN }}
          fetch-depth: 0

      - uses: ./.github/actions/ruby-cache

      - run: bundle exec fastlane merge_main
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_API_TOKEN }}
