name: Stress Tests

on:
  schedule:
    - cron: '0 1 * * *' # run at 1AM UTC
  workflow_dispatch:

env:
  HOMEBREW_NO_INSTALL_CLEANUP=1: 1 # Disable cleanup for homebrew, we don't need it on CI

jobs:
  v3-stress-tests:
    name: Run Stress Tests (Debug)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - name: Run bootstrap.sh
      run: ./bootstrap.sh
    - name: Run Stress Tests
      run: bundle exec fastlane stress_test

  v3-stress-tests_release:
    name: Run Stress Tests (Release)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - name: Run bootstrap.sh
      run: ./bootstrap.sh
    - name: Run Stress Tests
      run: bundle exec fastlane stress_test_release

  build-and-test-v3-ios11:
    name: Run v3 Tests (iOS11.4)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache RubyGems
      uses: actions/cache@v2
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Cache Mint
      uses: actions/cache@v2
      id: mint-cache
      with:
        path: /usr/local/lib/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('./Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - name: Run bootstrap.sh
      run: ./bootstrap.sh
    - name: Install iOS11.4 runtime
      run: bundle exec xcversion simulators --install='iOS 11.4'
    - name: Run v3 Tests (Debug - iOS 11.4)
      run: bundle exec fastlane test device:"iPhone 7 (11.4)"
    - name: Post Codecov report
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
