name: Nightly
    
on:
  push:
    branches:
      - master

jobs:
  nightly:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache Carthage dependencies
      uses: actions/cache@v1.1.0
      id: carthage-cache
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-stable-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-stable-
    - name: Cache RubyGems
      uses: actions/cache@v1
      id: rubygem-cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    - name: Install Carthage dependencies
      if: steps.carthage-cache.outputs.cache-hit != 'true'
      run: echo 'BUILD_LIBRARY_FOR_DISTRIBUTION=YES'>/tmp/config.xcconfig; XCODE_XCCONFIG_FILE=/tmp/config.xcconfig carthage update --platform iOS --new-resolver --no-use-binaries --cache-builds; rm /tmp/config.xcconfig
    - name: Install RubyGems
      if: steps.rubygem-cache.outputs.cache-hit != 'true'
      run: bundle install
    - name: Install firebase-tools
      run: npm install -g firebase-tools
    - name: Run beta lane on fastlane for nightly build
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: bundle exec fastlane beta
