name: Smoke Checks LLC

on:
  push:
    branches:
      - develop
      - main

  pull_request:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1 # Disable cleanup for homebrew, we don't need it on CI
  IOS_SIMULATOR_DEVICE: "iPhone 16 Pro (18.1)"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PR_NUM: ${{ github.event.pull_request.number }}

jobs:
  test-llc-debug:
    name: Test LLC (Debug)
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 100
    - uses: ./.github/actions/bootstrap
      env:
        INSTALL_YEETD: true
        INSTALL_SONAR: true
    - uses: ./.github/actions/python-cache
    - name: Run LLC Tests (Debug)
      run: bundle exec fastlane test device:"${{ env.IOS_SIMULATOR_DEVICE }}"
      timeout-minutes: 60
    - name: Run Sonar analysis
      run: bundle exec fastlane sonar_upload
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "You shall not pass!"
        job_name: "Test LLC (Debug)"
        fields: message,commit,author,action,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: ${{ github.event_name == 'push' && failure() }}
    - name: Parse xcresult
      if: failure()
      run: |
        brew install chargepoint/xcparse/xcparse
        xcparse logs fastlane/test_output/StreamChat.xcresult fastlane/test_output/logs/
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Test Data LLC
        path: |
          fastlane/test_output/logs/*/Diagnostics/**/*.txt
          fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
